language: ruby

matrix:
  include:
    - os: linux
      rvm: 2.2.2
    - os: linux
      rvm: 2.2.1
    - os: linux
      rvm: 1.9.3
    - os: linux
      rvm: 1.8.7
    - os: osx
      rvm: 2.2.2
    - os: osx
      rvm: 2.2.1
    - os: osx
      rvm: 1.9.3


